<div class="hidden">
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-fireweed.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-fireweed.jpg" alt="fireweed growing near Lake Iliamna in Alaska" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-fall.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-fall.jpg" alt="shot of Lake Iliamna in the fall" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-mountains.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-mountains.jpg" alt="Lake Iliamna with mountains in the background" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-aerial.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-aerial.jpg" alt="aerial view of Lake Iliamna" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-trees.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-trees.jpg" alt="Lake Iliamna surrounded by trees" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-flowers.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-flowers.jpg" alt="Lake Iliamna behind purple flowers" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-airplane.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-airplane.jpg" alt="Lake Iliamna shot from under airplane wing" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-shallow.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-shallow.jpg" alt="shallow water at Lake Iliamna in Alaska" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-mountain.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-mountain.jpg" alt="Lake Iliamna with a mountain in the background" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-bear.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-bear.jpg" alt="bear drinking from shore on Lake Iliamna" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-mirror.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-mirror.jpg" alt="Lake Iliamna with sky mirrored" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-silouette.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-silouette.jpg" alt="Lake Iliamna with snow-capped mountains in the background and a silouetted tree in the foreground" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-plane.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-plane.jpg" alt="sea plane on Lake Iliamna" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-frozen.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-frozen.jpg" alt="aerial shot of a frozen Lake Iliamna" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-tributary.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-tributary.jpg" alt="tributary of Lake Iliamna" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-seaplane.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-seaplane.jpg" alt="seaplane parked on Lake Iliamna" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-above.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-above.jpg" alt="Lake Iliamna from above" /></a>
  <a class="fancybox" rel="lake-iliamna" href="/_assets/img/galleries/lake-iliamna-volcano.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-iliamna-volcano.jpg" alt="sea plane on Lake Iliamna with volcano in the background" /></a>
</div>
