<div class="hidden">
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-aerial.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-aerial.jpg" alt="aerial shot of Lake Clark National Park" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-airplane.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-airplane.jpg" alt="Lake Clark National Park as seen from airplane" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-fireweed.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-fireweed.jpg" alt="fireweed growing at Lake Clark National Park" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-frozen.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-frozen.jpg" alt="glacier Lake Clark National Park" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-ice.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-ice.jpg" alt="mountaintop view of Lake Clark National Park in Alaska" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-mirror.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-mirror.jpg" alt="plane wing in Lake Clark" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-panoramic.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-panoramic.jpg" alt="Lake Clark" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-shore.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-shore.jpg" alt="sea plane shown through trees at Lake Clark National Park" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-snow.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-snow.jpg" alt="sandbar at Lake Clark National Park in Alaska" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-tributary.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-tributary.jpg" alt="glacier at Lake Clark National Park in Alaska in snow" /></a>
  <a class="fancybox" rel="lake-clark" href="/_assets/img/galleries/lake-clark-volcano.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/lake-clark-volcano.jpg" alt="Novarupta volcano in Lake Clark National Park" /></a>
</div>
