<div class="hidden">
  <a class="fancybox" rel="sockeye-salmon" href="/_assets/img/galleries/sockeye-salmon-alaska.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/sockeye-salmon-alaska.jpg" alt="sockeye salmon" /></a>
  <a class="fancybox" rel="sockeye-salmon" href="/_assets/img/galleries/sockeye-salmon-bristolbay.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/sockeye-salmon-bristolbay.jpg" alt="sockeye salmon" /></a>
  <a class="fancybox" rel="sockeye-salmon" href="/_assets/img/galleries/sockeye-salmon-clear.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/sockeye-salmon-clear.jpg" alt="sockeye salmon" /></a>
  <a class="fancybox" rel="sockeye-salmon" href="/_assets/img/galleries/sockeye-salmon-group.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/sockeye-salmon-group.jpg" alt="sockeye salmon" /></a>
  <a class="fancybox" rel="sockeye-salmon" href="/_assets/img/galleries/sockeye-salmon-red.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/sockeye-salmon-red.jpg" alt="sockeye salmon" /></a>
  <a class="fancybox" rel="sockeye-salmon" href="/_assets/img/galleries/sockeye-salmon-spawning.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/sockeye-salmon-spawning.jpg" alt="sockeye salmon" /></a>
  <a class="fancybox" rel="sockeye-salmon" href="/_assets/img/galleries/sockeye-salmon-thrash.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/sockeye-salmon-thrash.jpg" alt="sockeye salmon" /></a>
  <a class="fancybox" rel="sockeye-salmon" href="/_assets/img/galleries/sockeye-salmon-water.jpg"><img class="lazy" property="Photograph" src="/_assets/img/galleries/sockeye-salmon-water.jpg" alt="sockeye salmon" /></a>
</div>